# Generated by Django 6.0.3 on 2026-03-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_natcashtopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('livre', 'Livré')], default='en_cours', max_length=20),
        ),
    ]
