# Generated by Django 6.0.3 on 2026-03-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_purchase_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('expedie', 'Expédié'), ('livre', 'Livré')], default='en_cours', max_length=20),
        ),
    ]
