# Generated by Django 6.0.3 on 2026-03-12 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_purchase_statut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NatCashTopUp',
        ),
    ]
